# Generated by Django 2.0.2 on 2019-01-16 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('DNI', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('correo', models.EmailField(max_length=30)),
                ('fecha', models.DateTimeField()),
                ('genero', models.CharField(max_length=1)),
            ],
        ),
    ]
