# Generated by Django 2.0.2 on 2019-01-17 03:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('perfiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('DNI', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('fecha', models.DateTimeField()),
                ('genero', models.CharField(max_length=1)),
            ],
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('perfil_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='perfiles.Perfil')),
                ('programa', models.CharField(max_length=50)),
            ],
            bases=('perfiles.perfil',),
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('perfil_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='perfiles.Perfil')),
                ('horas_totales', models.IntegerField()),
                ('horas', models.IntegerField()),
            ],
            bases=('perfiles.perfil',),
        ),
        migrations.AddField(
            model_name='perfil',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
