# Generated by Django 2.0.6 on 2019-03-16 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0002_auto_20190116_2211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='perfil_ptr',
        ),
        migrations.RemoveField(
            model_name='monitor',
            name='perfil_ptr',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Estudiante',
        ),
        migrations.DeleteModel(
            name='Monitor',
        ),
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
