# Generated by Django 2.1.7 on 2019-03-24 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('perfiles', '0003_auto_20190316_0420'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_admin', models.SmallIntegerField(default=0, verbose_name='Id')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=200, verbose_name='Apellidos')),
                ('email', models.EmailField(blank=True, max_length=100, verbose_name='Email')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Administrador',
                'verbose_name_plural': 'Administradores',
                'ordering': ['id_admin', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='Advisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_advisor', models.SmallIntegerField(default=0, verbose_name='Id')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=200, verbose_name='Apellidos')),
                ('birthdate', models.DateTimeField(verbose_name='Fecha de nacimiento')),
                ('gender', models.CharField(max_length=200, verbose_name='Genero')),
                ('hours', models.SmallIntegerField(default=0, verbose_name='Horas Asignadas')),
                ('subject', models.CharField(max_length=200, verbose_name='Materia asignada')),
                ('email', models.EmailField(blank=True, max_length=100, verbose_name='Email')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Monitor',
                'verbose_name_plural': 'Monitores',
                'ordering': ['id_advisor', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_student', models.SmallIntegerField(default=0, verbose_name='Id')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=200, verbose_name='Apellidos')),
                ('email', models.EmailField(blank=True, max_length=100, verbose_name='Email')),
                ('birthdate', models.DateTimeField(verbose_name='Fecha de nacimiento')),
                ('gender', models.CharField(max_length=200, verbose_name='Genero')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'ordering': ['id_student', 'last_name'],
            },
        ),
    ]
