# Generated by Django 2.1.7 on 2019-03-24 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subject', '0001_initial'),
        ('perfiles', '0004_admin_advisor_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='subjects',
            field=models.ManyToManyField(related_name='subjects', to='subject.Subject'),
        ),
        migrations.AddField(
            model_name='advisor',
            name='estudiantes',
            field=models.ManyToManyField(related_name='Estudiantes', to='perfiles.Student'),
        ),
    ]
