# Generated by Django 2.2.2 on 2019-06-17 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_subject_assigned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='subject_assigned',
            field=models.ManyToManyField(blank=True, to='subjects.Subject', verbose_name='Asignaturas asignadas'),
        ),
    ]
