# Generated by Django 2.2.2 on 2019-06-17 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190617_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type_user',
            field=models.CharField(choices=[('Superuser', 'Superuser'), ('Admin', 'Admin'), ('Student', 'Student'), ('Monitor', 'Monitor')], max_length=30),
        ),
    ]
