# Generated by Django 2.2.2 on 2019-06-23 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190617_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image_profile',
            field=models.ImageField(blank=True, upload_to='profile/'),
        ),
    ]
