# Generated by Django 2.2.2 on 2019-06-26 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190623_0225'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hours',
            field=models.IntegerField(default=0, verbose_name='Usuario'),
        ),
    ]
