# Generated by Django 2.2.2 on 2019-06-26 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hours',
            field=models.IntegerField(null=True, verbose_name='horas por cumplir'),
        ),
    ]
