# Generated by Django 2.2.2 on 2019-06-26 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20190625_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hours',
            field=models.IntegerField(default=0, verbose_name='horas por cumplir'),
        ),
    ]
