# Generated by Django 2.2.2 on 2019-06-26 01:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20190625_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2019, 6, 25, 20, 57, 19, 77043), verbose_name='Fecha de nacimiento'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='hours',
            field=models.IntegerField(verbose_name='Horas por cumplir'),
        ),
    ]
