# Generated by Django 2.2.2 on 2019-06-26 01:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20190625_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2019, 6, 26, 1, 59, 23, 42483, tzinfo=utc), verbose_name='Fecha de nacimiento'),
        ),
    ]
