# Generated by Django 2.2.2 on 2019-06-26 02:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20190625_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2019, 6, 26, 2, 49, 2, 747373, tzinfo=utc), verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], default='Masculino', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='hours',
            field=models.IntegerField(default=0, verbose_name='Horas por cumplir'),
        ),
    ]
