# Generated by Django 2.2.2 on 2019-06-26 02:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20190625_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2019, 6, 26, 2, 54, 37, 534326, tzinfo=utc), verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(default='Masculino', max_length=30),
        ),
    ]
