# Generated by Django 2.2.2 on 2019-06-26 03:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20190625_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 26, 3, 41, 37, 59523, tzinfo=utc), verbose_name='Fecha de nacimiento'),
        ),
    ]
