# Generated by Django 2.2.2 on 2019-06-26 03:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20190625_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2019, 6, 26, 3, 42, 40, 981027, tzinfo=utc), verbose_name='Fecha de nacimiento'),
        ),
    ]
