# Generated by Django 2.2.2 on 2019-06-20 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests_users', '0002_requestuser_date_request'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestuser',
            old_name='date_request',
            new_name='request_date',
        ),
    ]
