# Generated by Django 2.2.2 on 2019-06-20 20:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_users', '0003_auto_20190620_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestuser',
            name='request_date',
        ),
        migrations.AddField(
            model_name='requestuser',
            name='requested_time',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Fecha de solicitud'),
        ),
    ]
