# Generated by Django 2.2.2 on 2019-06-23 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_users', '0004_auto_20190620_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestuser',
            name='state',
            field=models.CharField(choices=[('Requested', 'Requested'), ('Accepted', 'Accepted'), ('Declined', 'Declined'), ('Finished', 'Finished')], max_length=30, verbose_name='Estado de la solicitud'),
        ),
    ]
