# Generated by Django 2.2.2 on 2019-06-26 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_users', '0005_auto_20190623_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestuser',
            name='state',
            field=models.CharField(choices=[('Requested', 'Requested'), ('Accepted', 'Accepted'), ('Declined', 'Declined'), ('FinishedMonitor', 'FinishedMonitor'), ('FinishedEstudent', 'FinishedEstudent')], max_length=30, verbose_name='Estado de la solicitud'),
        ),
    ]
